schedules:
- cron: "0 0 * * *"
  displayName: "Nightly Build"
  branches:
    include:
    - 'master'

jobs:
- template: ./ci.yml
  parameters:
    maxParallel: 1 # any more and we get throttled by AzDO!

    goVersions:
    - value: '1.13.1'
      ymlSafeName: '1_13_1'

    vmImages:
    - value: 'macOS-10.14'
      ymlSafeName: 'macos_10_14'
  
    - value: 'ubuntu-16.04'
      ymlSafeName: ubuntu_16_04
