schedules:
- cron: "*/1 * * * 1-5"
  displayName: Daily midnight build
  branches:
    include:
    - master
    - test
  always: false

trigger: none
pr: none



steps:
- script: echo Hello, world!!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
